### ISSUE TITLE
Unable to get rapidast to parse OpenAPI

### ISSUE THREAD

**Issue by sarroutbi** [RedHatProductSecurity/rapidast#121]
I am trying to make rapidast work on my operator in top of OpenShift 4.14, but I am not able to do so.

rapidast-job is crashing, reporting this error:

```bash
tomation plan failures:
        Job openapi target: https://api.ci-...rhcloud.com:6443: Failed to parse OpenAPI definition.
```
Configuration of my cluster is as follows:
```bash
$ oc config view
...
server: https://api.ci-...rhcloud.com:6443
...
```

What is the correct URL to use in the configuration? I have next one:
```bash
application:
    shortName: "tangservers"
    url: "https://api.ci...rhcloud.com:6443/openapi/v2"
```
I have tried without openapi/v2 and without v2, with no success. However, next commands work appropriately:
```bash
oc get --raw /openapi/v3
oc get --raw /openapi/v2
```

Is there any OpenShift based configuration I can check anywhere?

Thanks!!!

**Comment by jeremychoi** [comment]
I'm quite certain it is complaining about parsing the openapi file specified in `scanners.zap.apiScan.apis.apiUrl`. could you try setting the apiUrl to the one of openapi v3, instead of v2: e.g, 
https://...6443/openapi/v3/apis/daemons.redhat.com/v1alpha1/namespaces/nbde/tangservers?

In addition, once the parsing issue is clear, the application.url should be "https://api.ci...rhcloud.com:6443/", without 'openapi/v2'

**Comment by sarroutbi** [comment]
Hello Jeremy. I made proposed changes, no success:

Automation plan failures:
        Job openapi target: https://...6443/ invalid API URL: https://...:6443/openapi/v3/apis/daemons.redhat.com/v1alpha1/namespaces/nbde/tangservers

**Comment by sarroutbi** [comment]
I was able to save an OpenAPI file that was valid and upload it to the container. With that, it worked!!! Thanks @cedricbu , @jeremychoi !!!
